### ISSUE TITLE
Extending Mathosphere

### ISSUE THREAD

**Issue by AndreG-P** [ag-gipp/math2vec#11]
@physikerwelt 
In mathosphere gibt es ein paar Programme die man starten kann (siehe [Main.java](https://github.com/ag-gipp/mathosphere/blob/master/mathosphere-core/src/main/java/com/formulasearchengine/mathosphere/mlp/Main.java)).

Mit MLP gibt es die möglichkeit MLP auszuführen. Der berechnet dann die scores der definien-identifier paare nur anhand der Distanzen. Ich denke die Ergebnisse davon lagen bei run 30% precision oder so?
Dann gibt es ML der den WekaLearner implementiert. (50% precision).

Dann gibt es noch ein paar andere Programme, von denen ich gerade nicht weiß was sie machen.

Die Frage ist, was sollten wir jetzt am besten erweitern? Den WekaLearner hab ich nie dazu bringen können die selben Resultate zu erzeugen wie sie im Paper waren.

Ich hätte 2 Ideen die sich unterschiedlich leicht ausprobieren ließen.

1. Wir fragen Word2Vec nach den besten Ergebnissen und ergänzen diese zu den Ergebnissen vom MLP (mit oder ohne learning...) bzw wir gewichten die Ergebnisse vom MLP mit Word2Vec neu. Das hätte den Vorteil das wir auch Einträge bekommen könnten, die nicht namentlich im Paper erwähnt werden, weil sie global als allgemein Bekannt angenommen werden.
2. Wir extrahieren den Absatz mit dem Identifier und fragen Doc2Vec nach ähnlichen Paragraphen aus dem Arxiv Korpus. Auf diesen ähnlichen Absätzen können wir dann MLP anwenden, der dann (soweit die Theorie) viel bessere Werte generieren müsste, weil sich alle Absätze ja halbwegs ähneln sollten. Wie das mit dem WekaLearner gehen soll weiß ich aber nicht. Wir müssten eigentlich das trainierte Model laden vom Learner und dann nur die Ergebnisse analysieren. Aber das hat ja nie geklappt.

Ein weiteres Problem, wir haben MLP (den wekalearner) nie auf den neuen Goldstandard angewant, weil wir nicht so leicht an die Quellen gekommen sind. Das eine ist DLMF, das andere arxiv und die ersten 100 sind von Wikipedia. Wir stehen damit wieder vorm selben problem, wenn wir den neuen Goldstandard evaluieren wollen.

PS @truas sorry I will explain that tomorrow to you

**Comment by physikerwelt** [comment]
We discussed this extensively and will implement a similar idea based on this concept.
